### ISSUE TITLE
brew tap fwartner/mac-cleanup broken

### ISSUE THREAD

**Issue by potpot59** [fwartner/homebrew-mac-cleanup#52]
Running `brew tap fwartner/mac-cleanup` doesn't work:

> ==> Tapping fwartner/mac-cleanup
> Cloning into '/usr/local/Homebrew/Library/Taps/fwartner/homebrew-mac-cleanup'...
> Username for 'https://github.com': XXX
> Password for 'https://XXX@github.com':
> remote: Repository not found.
> fatal: repository 'https://github.com/fwartner/homebrew-mac-cleanup/' not found
> Error: Failure while executing; `git clone https://github.com/fwartner/homebrew-mac-cleanup /usr/local/Homebrew/Library/Taps/fwartner/homebrew-mac-cleanup` exited with 128.

**Comment by piersolenski** [comment]
Same here :'(

**Comment by syfless1999** [comment]
you can directly use this:
```powershell
$ git clone git@github.com:fwartner/mac-cleanup.git /usr/local/Homebrew/Library/Taps/fwartner/homebrew-mac-cleanup
```
and then `brew install mac-cleanup`

**Comment by mike-hmg** [comment]
It's because the git repo is incorrect on the brew tap. It should read "https://github.com/fwartner/mac-cleanup/", but instead it is trying to pull "https://github.com/fwartner/homebrew-mac-cleanup/".

**Comment by x7a** [comment]
@syfless1999 that doesn't work for me.
```
Cloning into '/usr/local/Homebrew/Library/Taps/fwartner/homebrew-mac-cleanup'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by syfless1999** [comment]
> @syfless1999 that doesn't work for me.
> 
> ```
> Cloning into '/usr/local/Homebrew/Library/Taps/fwartner/homebrew-mac-cleanup'...
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ```

maybe permission problem, try to use `sudo su` and then clone

**Comment by x7a** [comment]
@syfless1999 still getting the exact same error

**Comment by syfless1999** [comment]
@x7a [https://stackoverflow.com/questions/2643502/how-to-solve-permission-denied-publickey-error-when-using-git](https://stackoverflow.com/questions/2643502/how-to-solve-permission-denied-publickey-error-when-using-git)
this answer maybe useful

**Comment by fwartner** [comment]
Could be because of the naming of the repository. Renamed it.

**Comment by x7a** [comment]
@fwartner still can't install. I get `Error: SHA256 mismatch`. I don't think it is worth it to rename the repo. It can be definitely done differently.

**Comment by x7a** [comment]
@fwartner still can't install. I get `Error: SHA256 mismatch`.
