### ISSUE TITLE
LOL

### ISSUE THREAD

**Issue by pie6k** [fwartner/homebrew-mac-cleanup#56]
It's not really an issue, but:

1. Wanted to get it as my disc is full
2. Trying to download, but it asks me to update xcode
3. Trying to update xcode
4. Nope, "not enough of disc space to download code"

💩

**Comment by potpot59** [comment]
You use homebrew? Maybe try to install it with curl or wget

**Comment by pie6k** [comment]
![image](https://user-images.githubusercontent.com/7311462/109384118-fb603a00-78ea-11eb-8766-1ae5219cf445.png)
