### ISSUE TITLE
running the Step by Step Install does not work

### ISSUE THREAD

**Issue by daniloab** [fwartner/homebrew-mac-cleanup#59]
when I try via `Step by Step Install` does not work for me, returning the follow error:

```
MacBook-Pro:projects entria$ cleanup
/usr/local/bin/cleanup: line 1: 404:: command not found
```

via homebrew works running `mac-cleanup`

**Comment by fwartner** [comment]
If it’s working for you via the brew installation, you can create an alias for „mac-cleanup“ to „cleanup“.

Should do the trick. :)
Am 11. März 2021, 13:05 +0100 schrieb Danilo Assis ***@***.***>:

**Comment by daniloab** [comment]
Nice, I opened the issue just to remember for the next time I will use! But, its a huge work, thanks
