### ISSUE TITLE
404 Command not found

### ISSUE THREAD

**Issue by kzkpro** [fwartner/homebrew-mac-cleanup#64]
after installing  cleanup. when i run cleanup, i got `/usr/local/bin/cleanup: line 1: 404:: command not found` error. i had to download repo update this line `sudo mv cleanup /usr/local/bin/cleanup` to `sudo mv cleanup.sh /usr/local/bin/cleanup` in installer.sh and run the installer.sh. then it worked. hope this help if someone face similar error. Thanks!

**Comment by mrtrkmn** [comment]
```
curl -o cleanup https://raw.githubusercontent.com/fwartner/homebrew-mac-cleanup/master/mac-cleanup
chmod +x cleanup
sudo mv cleanup /usr/local/bin/cleanup
```

**Comment by fwartner** [comment]
Fixed! Thank you!
